version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum update -y
      - yum install -y --allowerasing gcc make openssl jq
      - npm install -g @angular/cli
      - npm install  # Install project dependencies

  build:
    commands:
      - echo Building Angular application...
      - ng build --configuration=production  # Replace with your build command

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
