version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum update -y
      - yum install -y --allowerasing gcc make openssl jq
      - npm install -g @angular/cli
      - npm install  # Install project dependencies

  build:
    commands:
      - echo Building Angular application...
      - ng build --configuration=production  # Replace with your build command

  post_build:
    commands:
      - echo Copying build artifacts...
      - if [ -d "dist/sumitech" ]; then cp -r dist/sumitech/* $CODEBUILD_SRC_DIR/; else echo "No dist/sumitech directory found"; fi

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/sumitech'
